# Generated by Django 5.0.1 on 2024-01-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymodel',
            name='appearance',
            field=models.TextField(max_length=200),
        ),
    ]
