# Generated by Django 5.0.1 on 2024-01-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0002_alter_familymodel_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymodel',
            name='image',
            field=models.ImageField(default='templates/family_tree/assets/family_members/Not_Found.jpg', upload_to='templates/family_tree/assets/family_members/'),
        ),
        migrations.AlterField(
            model_name='familymodel',
            name='appearance',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
